services:
  ner-linking-api:
    container_name: ner-linking-api
    build: .
    user: root
    environment:
      DICTIONARY_FILE:
      LANGUAGE: es
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    restart: unless-stopped
    privileged: true

networks:
  default:
    name: cogstack-net
    external: true
